# Generated by Django 5.0.3 on 2024-03-11 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tags",
            options={"verbose_name": "Tag", "verbose_name_plural": "Tags"},
        ),
    ]
