# Generated by Django 5.0.3 on 2024-03-11 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0003_alter_task_done_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ["-done_at", "-created_at"]},
        ),
    ]
