# Generated by Django 5.0.3 on 2024-03-11 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0004_alter_task_options"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Tags",
            new_name="Tag",
        ),
        migrations.AlterModelOptions(
            name="tag",
            options={},
        ),
    ]
