from django.urls import path

from todo.views import (
    index,
    TaskCreateView,
    TaskDeleteView,
    TaskDetailView,
    TaskListView,
    TaskUpdateView,
    TagCreateView,
    TagListView,
    TagDeleteView,
    TagUpdateView,
    mark_as_done,
    undo_mark_as_done,
    TagDetailView,
)

app_name = "todo"

urlpatterns = [
    path("", index, name="index"),
    path("tasks/",
         TaskListView.as_view(),
         name="task-list"),
    path("tasks/<int:pk>/,",
         TaskDetailView.as_view(),
         name="task-detail"),
    path("tasks/<int:pk>/delete/",
         TaskDeleteView.as_view(),
         name="task-delete"),
    path("tasks/<int:pk>/update/",
         TaskUpdateView.as_view(),
         name="task-update"),
    path("task_create/",
         TaskCreateView.as_view(),
         name="task-create"),
    path("tag_create/",
         TagCreateView.as_view(),
         name="tag-create"),
    path("tags/",
         TagListView.as_view(),
         name="tag-list"),
    path("tags/<int:pk>/delete/",
         TagDeleteView.as_view(),
         name="tag-delete"),
    path("tags/<int:pk>/update/",
         TagUpdateView.as_view(),
         name="tag-update"),
    path("mark-as-done/<int:task_id>/",
         mark_as_done,
         name="mark-as-done"),
    path("undo-mark-as-done/<int:task_id>/",
         undo_mark_as_done,
         name="undo-mark-as-done"),
    path("tags/<int:pk>/",
         TagDetailView.as_view(),
         name="tags-detail"),
]
